version: '3.9'
services:
    web:
        container_name: coursework5-web
        build: .
        command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - ./backend:/code
            - static_volume:/usr/share/nginx/html/static
            - media_volume:/usr/share/nginx/html/media
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
            - cache

    db:
        image: postgres:16
        container_name: coursework5-db
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env

    cache:
        image: redis:alpine
        container_name: coursework5-cache
        ports:
            - "6379:6379"

    celery:
        container_name: coursework5-celery
        build: .
        command: bash -c "celery -A project worker -l info"
        volumes:
            - ./:/code
        env_file:
            - .env
        depends_on:
            - cache

    celery-beat:
        container_name: coursework5-celery-beat
        build: .
        command: bash -c "celery -A project beat -l info"
        volumes:
            - ./:/code
        env_file:
            - .env
        depends_on:
            - cache

    frontend:
        build: .
        container_name: coursework5-frontend
        command: npm start

    nginx:
        container_name: coursework5-nginx
        build: .
        ports:
            - "80:80"
        volumes:
            - static_volume:/usr/share/nginx/html/static
            - media_volume:/usr/share/nginx/html/media
        depends_on:
            - web

volumes:
    pgdata:
    static_volume:
    media_volume: