# Generated by Django 5.2.3 on 2025-07-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "place",
                    models.CharField(
                        help_text="Напиши место",
                        max_length=255,
                        verbose_name="Место для выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Время для выполнения привычки",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Напиши что делаешь",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(default=False, help_text="Приятная привычка?"),
                ),
                (
                    "last_performed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата и время последнего выполнения",
                        null=True,
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Периодичность в днях"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="чем пользователь должен себя вознаградить после выполнения",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время на выполнение в минутах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Публичная привычка?"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная полезная привычка",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habitatom.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
