# Generated by Django 5.2.3 on 2025-07-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=255)),
                (
                    "is_pleasant",
                    models.BooleanField(default=False, help_text="Приятная привычка?"),
                ),
                ("last_performed", models.DateField(blank=True, null=True)),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Периодичность в днях"
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255)),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время на выполнение в минутах"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Публичная привычка?"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная полезная привычка",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habitatom.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
